### PR TITLE
Add Support for Shiny

### PR DESCRIPTION
**Pull request by JohnCoene**
Hi Chales,

Great, package thank you very much!

This PR brings support for Shiny, I added an example in the README too.

### CODE REVIEW

**Comment by cfmack** [comment]
Awesome!  I will look into this tonight or in the weekend.   Thank you!   I can definitely use some assistance

**Comment by JohnCoene** [comment]
Great, thank you. Sorry, some of the checks don't pass; I'm really not used to {renv}. Let me know if you want me to change anything.

**Comment by cfmack** [comment]
I'll mess with renv as I need to update the dependencies.   Master will be unstable but we'll keep 1.0.1 stable until then.  I've tried to get this into CRAN (via submission) but have not been able to get a response.  Have you done that successfully?

**Comment by JohnCoene** [comment]
Yes, I have a few packages on CRAN. It's not always easy but this should be accepted. I'll do another PR to change some things that I know CRAN checks require :)

**Comment by JohnCoene** [comment]
What is that failed in your initial CRAN submission? 

It looks good to me, there are examples that can be run, it passes checks, etc.

A few things that might have been raised by the CRAN submission

https://github.com/cfmack/pRometheus/blob/ab7b99ec9c82d8239ca4dea09982fb70896c6cd9/DESCRIPTION#L3

This won't pass Prometheus should be between single quotes: 'Prometheus' (it's a brand~ish). Also you should not have "this is a package" or "for R" in there.

Also here, "This R package" should not be there.

https://github.com/cfmack/pRometheus/blob/ab7b99ec9c82d8239ca4dea09982fb70896c6cd9/DESCRIPTION#L9

In case you don't know (sorry if you do, not trying to appear condescending, just trying to help) run `devtools::check_win_devel()` before you submit this will run tests remotely on a windows as CRAN does. The local `devtools::check()`, travis, etc. Differ slightly from CRAN checks. 

Also use `usethis::use_cran_comments` to create the CRAN comments. You should have 1 NOTE (new submission) but everything else should be good to go. `devtools::check_win_devel()` should also only have 1 NOTE (new submission) and nothing else.

I would also check [rhub](https://r-hub.github.io/rhub/) it will let you run the checks on various machines, `rhub::check_for_cran` is pretty good though do not be alarmed by some of the warnings or errors that come out of it, it can be iffy I found.

Then `devtools::release_checks()` is pretty good too for basic checks.

When all is done submit with `devtools::submit_cran`, it'll use the `.md` created by `usethis::use_cran_comments`.

Hope that helps a bit, don't hesitate if you think I can help further!

**Comment by cfmack** [comment]
I did not get a reply from CRAN, albeit some can imagine it hit my spam folder.  Regardless, I'll give these notes ago.  Thank you!

**Comment by cfmack** [comment]
As an FYI, I got renv updated.

**Pull request merged**
